version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "12222:12222"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - 'C:\Certbot\live\haoweivmsea.southeastasia.cloudapp.azure.com\fullchain.pem:/etc/nginx/certs/fullchain.pem:ro'
      - 'C:\Certbot\live\haoweivmsea.southeastasia.cloudapp.azure.com\privkey.pem:/etc/nginx/certs/privkey.pem:ro'
    extra_hosts:
      - "host.docker.internal:host-gateway"